const QUESTIONS = [
{question:"Who built the ark?", choices:["Moses","Noah","David","Abraham"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who was swallowed by a big fish?", choices:["Jonah","Peter","Paul","Elijah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who led Israel out of Egypt?", choices:["Moses","Joshua","Aaron","Samuel"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who killed Goliath?", choices:["Saul","David","Solomon","Samson"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who was Jesus' mother?", choices:["Mary","Martha","Ruth","Sarah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Where was Jesus born?", choices:["Nazareth","Bethlehem","Jerusalem","Rome"], correctIndex: Math.floor(Math.random()*4)},
{question:"How many disciples did Jesus have?", choices:["10","11","12","13"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who betrayed Jesus?", choices:["Peter","Judas","John","Thomas"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who denied Jesus three times?", choices:["Peter","James","Paul","Andrew"], correctIndex: Math.floor(Math.random()*4)},
{question:"First book of the Bible?", choices:["Genesis","Exodus","Psalms","Matthew"], correctIndex: Math.floor(Math.random()*4)},

{question:"Last book of the Bible?", choices:["Jude","Revelation","Acts","Romans"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who built the temple?", choices:["David","Solomon","Saul","Nehemiah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Strongest man in the Bible?", choices:["Samson","David","Gideon","Elijah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who parted the Red Sea?", choices:["Joshua","Moses","Aaron","Elijah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Garden where Adam lived?", choices:["Eden","Zion","Bethel","Sinai"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who was thrown into lions' den?", choices:["Daniel","Joseph","Isaiah","Jacob"], correctIndex: Math.floor(Math.random()*4)},
{question:"Jesus turned water into?", choices:["Oil","Wine","Honey","Milk"], correctIndex: Math.floor(Math.random()*4)},
{question:"Tax collector disciple?", choices:["Matthew","Luke","Mark","John"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who baptized Jesus?", choices:["Peter","John the Baptist","Paul","James"], correctIndex: Math.floor(Math.random()*4)},
{question:"Jesus fasted for how many days?", choices:["7","30","40","50"], correctIndex: Math.floor(Math.random()*4)},

{question:"Who interpreted dreams in Egypt?", choices:["Joseph","Moses","Aaron","Samuel"], correctIndex: Math.floor(Math.random()*4)},
{question:"First man?", choices:["Adam","Noah","Abraham","Cain"], correctIndex: Math.floor(Math.random()*4)},
{question:"First woman?", choices:["Sarah","Mary","Eve","Ruth"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who built a huge boat?", choices:["Noah","David","Moses","Solomon"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who wrote many Psalms?", choices:["David","Paul","Peter","Isaiah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Jesus fed 5000 with?", choices:["Fish & bread","Rice","Fruit","Meat"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who walked on water with Jesus?", choices:["John","Peter","James","Andrew"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who saw the burning bush?", choices:["Moses","Elijah","Isaiah","Jacob"], correctIndex: Math.floor(Math.random()*4)},
{question:"Where did Jesus grow up?", choices:["Nazareth","Rome","Athens","Corinth"], correctIndex: Math.floor(Math.random()*4)},
{question:"Angel told Mary about Jesus?", choices:["Gabriel","Michael","Raphael","Uriel"], correctIndex: Math.floor(Math.random()*4)},

{question:"Who climbed sycamore tree?", choices:["Zacchaeus","Matthew","Peter","Luke"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who was first king of Israel?", choices:["Saul","David","Solomon","Samuel"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who anointed Saul as king?", choices:["Samuel","Elijah","Nathan","Moses"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who was thrown into a fiery furnace?", choices:["Shadrach","Meshach","Abednego","Daniel"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who wrote Revelation?", choices:["John","Paul","Peter","Luke"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who was sold into slavery by his brothers?", choices:["Joseph","Benjamin","Esau","Jacob"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who wrestled with an angel?", choices:["Jacob","Esau","Abraham","Isaac"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who is known for wisdom?", choices:["Solomon","David","Samuel","Elijah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who parted the Jordan River?", choices:["Joshua","Moses","Elijah","Aaron"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who denied Peter?", choices:["Jesus","Paul","John","Thomas"], correctIndex: Math.floor(Math.random()*4)},

{question:"Who betrayed Samson?", choices:["Delilah","Ruth","Esther","Martha"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who anointed David as king?", choices:["Samuel","Nathan","Elijah","Moses"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who wrote Genesis?", choices:["Moses","David","Solomon","Isaiah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who healed the blind man?", choices:["Jesus","Peter","Paul","Philip"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who built the walls of Jerusalem?", choices:["Nehemiah","Ezra","Solomon","David"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who fed Elijah by the ravens?", choices:["Elijah","Moses","David","Samuel"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who had a coat of many colors?", choices:["Joseph","Jacob","Esau","Benjamin"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who was swallowed by a whale?", choices:["Jonah","Peter","Paul","Elijah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who was the mother of Samuel?", choices:["Hannah","Sarah","Ruth","Martha"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who killed Abel?", choices:["Cain","Abel","Seth","Noah"], correctIndex: Math.floor(Math.random()*4)},
{question:"Who was Abraham's wife?", choices:["Sarah","Hagar","Rebekah","Leah"], correctIndex: Math.floor(Math.random()*4)},
];
